# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [8]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os



# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [9]:
city_data = "../city_data.csv"
city_data_df = pd.read_csv(city_data)
city_data_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
0,Ancud,CL,-41.8697,-73.8203,51.01,100,90,3.44,1618445435
1,Yangi Marg`ilon,UZ,40.4272,71.7189,53.60,76,100,4.00,1618445435
2,Arraial do Cabo,BR,-22.9661,-42.0278,69.80,83,40,2.30,1618445436
3,Hilo,US,19.7297,-155.0900,80.60,57,20,12.66,1618445782
4,Cheyenne,US,41.1400,-104.8203,26.60,93,90,13.80,1618445637
...,...,...,...,...,...,...,...,...,...
543,Kodīnar,IN,20.7903,70.7031,77.81,50,3,4.79,1618445624
544,Prince Rupert,CA,54.3161,-130.3201,51.80,62,1,5.75,1618445477
545,Malé,MV,4.1748,73.5089,81.97,75,41,8.86,1618445625
546,Katiola,CI,8.1333,-5.1000,78.80,83,20,2.30,1618445625
547,Ust'-Kulom,RU,61.6864,53.6902,48.79,89,93,11.01,1618445626

In [17]:
city_data_df.dtypes

City           object
Country        object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Date            int64
dtype: object

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [10]:
gmaps.configure(api_key=g_key)

In [14]:
# Store 'Lat' and 'Lng' into  locations 
locations = city_data_df[["Lat", "Lng"]]

In [19]:
#Humidity as weight.
humidity = city_data_df["Humidity"]

#Heatmap.
fig = gmaps.figure() #center=(46.0, -5.0), zoom_level=2
max_intensity = np.max(humidity)

# heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating = False, max_intensity = 100, point_radius = 3)
# fig.add_layer(heat_layer)
# fig

# Add Heatmap layer to map.
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 4)
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
#converting unix time to date & time
city_data_df['Date'] = pd.to_datetime(city_data_df['Date'],unit='s')
city_data_df['Date'] = pd.to_datetime(city_data_df['Date']).dt.date
city_data_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
0,Ancud,CL,-41.8697,-73.8203,51.01,100,90,3.44,2021-04-15
1,Yangi Marg`ilon,UZ,40.4272,71.7189,53.60,76,100,4.00,2021-04-15
2,Arraial do Cabo,BR,-22.9661,-42.0278,69.80,83,40,2.30,2021-04-15
3,Hilo,US,19.7297,-155.0900,80.60,57,20,12.66,2021-04-15
4,Cheyenne,US,41.1400,-104.8203,26.60,93,90,13.80,2021-04-15
...,...,...,...,...,...,...,...,...,...
543,Kodīnar,IN,20.7903,70.7031,77.81,50,3,4.79,2021-04-15
544,Prince Rupert,CA,54.3161,-130.3201,51.80,62,1,5.75,2021-04-15
545,Malé,MV,4.1748,73.5089,81.97,75,41,8.86,2021-04-15
546,Katiola,CI,8.1333,-5.1000,78.80,83,20,2.30,2021-04-15
547,Ust'-Kulom,RU,61.6864,53.6902,48.79,89,93,11.01,2021-04-15

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure